// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:rewo_supplier/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BankDetailsAdapter());
    registerAdapter(LocationAdapter());
    registerAdapter(MaterialTypesModelAdapter());
    registerAdapter(RegistrationStatusAdapter());
    registerAdapter(SupllierMediaAdapter());
    registerAdapter(UserModelAdapter());
  }
}
